set runtimepath^=~/.config/vim
set runtimepath+=~/.config/vim/after

execute pathogen#infect()

let mapleader = ","

nmap <Leader>n :NERDTreeToggle<CR>

nnoremap <Leader>q :Bdelete<CR>
nnoremap <Leader><Tab> :bnext<CR>
" nnoremap <Leader><S-Tab> :bprev<CR>
nnoremap <Leader>s :%s/\<<C-r><C-w>\>//g<Left><Left>
nnoremap <Leader>wn :match ExtraWhitespace /\s\+$/<CR>
nnoremap <Leader>wf :match<CR>

" Use ctrl-[hjkl] to select the active split!
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

nmap <c-n> :set invnumber<CR>

map <F3>:set invhls hls?<CR>
imap <F3> <Esc>:set invhls hls?<CR>i

map  <F6> :r !date<CR>
imap <F6> <Esc>:r !date<CR>i

map s :source $HOME/.config/vim/vimrc<CR>

"General settings {
    filetype plugin indent on       " Enable filetype detection
    set number                      " Display line numbers
    syntax on                       " Enable syntax highlighting
    set background=dark             " Use the dark solarized theme
    colorscheme slate
    set showmatch                   " Show the matching part of the pair for [] {} or ()
    set ruler                       " Show the ruler at the bottom
    let g:netrw_liststyle=3         " Use file tree appearance in explorer mode
    set undofile                    " Persist undo/redo after exiting VIM
    set undodir=~/.vim/vimundo/     " Don't scatter undo files all over the place
    set nocompatible
    set laststatus=2                " Always show the status line (file name, current mode, etc)
    set backspace=indent,eol,start
    set tabstop=4
    set shiftwidth=4
    set smarttab
    set softtabstop=4
    set expandtab
    set mouse-=a
    set shell=bash
    let c_syntax_for_h=1
    let perl_fold=1
    " let g:solarized_termtrans=1     " Fixes an issue with iTerm2 Solarized theme and background
    " colorscheme solarized           " Use the solarized color scheme from .vim/colors/
"}

"Paste {
    nnoremap <F2> :set invpaste paste?<CR>
    set pastetoggle=<F2>
    set showmode
"}"

"Split settings {
    set splitbelow                  " Create the new split below, instead of VIM's default
    set splitright                  " Create the new vertical split to the right, instead of VIM's default
"}

if has("autocmd")
    " Use actual tab chars specifically in Makefiles
    autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

    autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
    autocmd BufEnter * let &titlestring = $HOSTNAME . ":" . expand("%:p:~")

    function! IncSearch()
      if line2byte(line("$")) < 10000000
        set incsearch
      else
        set noincsearch
      endif
    endfunction

    autocmd BufReadPost * call IncSearch()

    " function! PoundComment()
    "   map - 0i# <ESC>j
    "   map _ :s/^\s*# \=//g<CR>j
    "   set comments=:#
    " endfunction

    " autocmd Filetype sh call PoundComment()
    " autocmd Filetype ruby call PoundComment()
endif

"ctrlp settings {
    set wildignore+=*/tmp/*,*.so,*.swp,*.zip

    let g:ctrlp_custom_ignore = {
        \ 'dir':  '\.git$\|\.hg$\|\.svn$\|italent\/html$\|clickthrough$',
        \ 'file': '\.exe$\|\.so$\|\.dll$\|\.pyc$\|\.orig$\|\.BACKUP\.\|\.BASE\.\|\.LOCAL\.\|\.REMOTE\.\|\.un\~$\|\.swp$',
        \ }

    let g:ctrlp_map = '<c-p>'
    let g:ctrlp_cmd = 'CtrlP'
"}

"nerdtree settings{
    let NERDTreeIgnore = ['\.pyc$']
"}

"minibuf settings{
    let g:miniBufExplMapWindowNavVim = 1
    let g:miniBufExplUseSingleClick = 1
    let g:miniBufExplMapWindowNavArrows = 1
    let g:miniBufExplMapCTabSwitchBufs = 0
    let g:miniBufExplModSelTarget = 1
    let g:miniBufExplMaxSize = 1
    let g:miniBufExplTabWrap = 1
"}

" " Paste mode on/off
" map <F4> :call TogglePaste()<CR>
" set pastetoggle=<F4>

" let paste_mode = 0

" func! TogglePaste()
"   if g:paste_mode == 0
"     set paste
"     let g:paste_mode = 1
"   else
"     set nopaste
"     let g:paste_mode = 0
"   endif
" return
" endfunc
" end
